### ISSUE TITLE
How to use Subzeo serialization if we request from hazelcast client. 

### ISSUE THREAD

**Issue by mukul4u2005** [jerrinot/subzero#10]
Hi

I configured the serialization on server side by using subzero as 

SubZero.useAsGlobalSerializer(hzConfig);

and my pojo class is not implementing the 'Serializable' interface, I think as per above statement it is not necessary to implement serialization as it is overriding internally.

If I run with the same configuration then it is failing.

Or should I implement Serializable. Please suggest.

**Comment by jerrinot** [comment]
@mukul4u2005: what version of SubZero do you use? The latest stable version support client configuration as well: `SubZero.useAsGlobalSerializer(clientConfig);` should work.

**Comment by mukul4u2005** [comment]
I am using subzero-all-0.6

**Comment by jerrinot** [comment]
it not neccessary to implement the `serializable` interface. Did you configure SubZero on both client and server sides? what error you are getting?

**Comment by mukul4u2005** [comment]
Yes it was not configured on client side it seems like it is working now. Thanks for your quick response

**Comment by jerrinot** [comment]
that's great to hear! Happy Hazelcasting!
