### ISSUE TITLE
Using the delegating form of UserSerilizationBuilder is not practical due to Kryo dependency being shaded

### ISSUE THREAD

**Issue by wneild** [jerrinot/subzero#13]
Trying to directly configure custom serializers from an external library with Kryo through a KryoConfigurer isn't possible because the Kryo dependency is shaded to info.jerrinot.subzero.relocated...

This makes it impossible to use custom serializers that register multiple special types internally, like so:

```
public class SubZeroGlobalSerializer extends AbstractGlobalUserSerializer {

    public SubZeroGlobalSerializer() {
        super(UserSerializerConfig.delegate(kryo -> {
            ImmutableListSerializer.registerSerializers(kryo);
        }));
    }
}
```

where `registerSerializers` expects the standard Kryo package com.esotericsoftware.kryo.

I see two possible solutions:
1) Don't shade Kryo
2) Pull and shade the https://github.com/magro/kryo-serializers artifact (maybe not an issue given some of the classes from this project are already written to be recognised?)

**Comment by jerrinot** [comment]
Good catch! There is already a version where Kryo is not shaded, perhaps this case should be documented better?

**Comment by jerrinot** [comment]
Alternatively there could be subzero-extra with the extra serializers. WDYT?

**Comment by wneild** [comment]
Ah, of course, that makes sense. I suppose it could be useful to add a caveat that Kryo is shaded but maybe the real problem is that I'm just not thorough enough :smile:.

Personally, I'm satisfied with just subzero-core and importing the serializer library myself. I don't think the benefits of having subzero-extra will be worth the cost of having to keep the dependency up to date with just the kryo-serializers as yet.

**Comment by gAmUssA** [comment]
+1 for `subzero-extra` or `subzero-contrib` for extra serializer (not only for Kryo)

**Comment by jerrinot** [comment]
closing as there is the `subzero-core`
