### ISSUE TITLE
Compatibility with Kotlin

### ISSUE THREAD

**Issue by chaschev** [jerrinot/subzero#21]
Tight coupling with shadow implementation of Kryo...

... makes impossible extending Serializers, as that would require provide two versions: one for the shadow implementation and the other for the real kryo used in app

Which at this point makes this lib unusable with Kotlin which requires some serializers coverage

**Comment by jerrinot** [comment]
related to https://github.com/jerrinot/subzero/issues/13

**Comment by jerrinot** [comment]
@chaschev: have you tried to use `subzero-core` artifact? 
That does not have the Kryo shaded in.
