### ISSUE TITLE
Enable creating a Kryo with custom ReferenceResolver implementation

### ISSUE THREAD

**Issue by acieplak** [jerrinot/subzero#24]
Hi,

It's rather an enhancement request, but in `KryoStrategy#newKryoInstance()` we create a Kryo with default `MapReferenceResolver`. I have found out that in some cases this implementation is a lot more slowly than others, e.g. `ListReferenceResolver`. The difference sometimes is about 10 times, which is a lot.
It would be nice to have some kind of system property, e.g. a `subzero.referenceresolver.class` where we could specify which `ReferenceResolver` implementation should be used.

**Comment by jerrinot** [comment]
@acieplak: you are right, thanks for the ping and your contribution!
