### ISSUE TITLE
subzero compression 

### ISSUE THREAD

**Issue by loudywen** [jerrinot/subzero#35]
Hi,
Currently, I am setting the defaultSerializer= CompatibleFieldSerializer and I noticed that the size of the data inserted to Hazelcast is almost the same as the actual data size.  Is this related to the serializer? Since if I use the default FieldSerializer I am able to see the size of the data reduced more than 70%.

**Comment by jerrinot** [comment]
well, the `CompatibleFieldSerializer` has a space overhead - it has to include more metadata. So increase memory usage is expected.
