### ISSUE TITLE
Add support for registering custom serializers

### ISSUE THREAD

**Issue by wneild** [jerrinot/subzero#6]
Unfortunately Kryo does not include support out-the-box for a lot of native JDK types and therefore it is necessary to register custom serializers to handle them. It should be possible to register these custom serializers through subzero. Currently the only workaround is to set up an adjacent, independently configured Kryo serializer instance and register it to hazelcast, per type, as a custom serializer.

A library of implementations for handling some of these unsupported types can be found here https://github.com/magro/kryo-serializers

**Comment by jerrinot** [comment]
@wneild: thanks for you suggestion!
Do you have an idea how to specify configuration? it's easy with programmatic configuration, but there is no way to pass arguments in declarative configuration.

**Comment by wneild** [comment]
@jerrinot I hadn't thought about that! One option might be to introduce the ability to define your own typed Serializer implementation that takes a Kryo serializer which internally uses a new strategy which registers the serializer to Kyro on instantiation.

What are your thoughts?

**Comment by jerrinot** [comment]
@wneild: I pushed a first prototype into master.

It introduces a few options how to configure custom Kryo serializers. 
The simplest one is to have a file named `subzero-serializers.properties` on your classpath. It expects following format:
```
some.package.YourClass=other.package.KryoSerializer
some.package.OtherClass=other.package.OtherKryoSerializer
```
It's simple to use, but each serializer has to have a non-arg constructor. 

The other option is to extend `Serializer` and then you can provide own [registrations](https://github.com/jerrinot/subzero/blob/2bd916e60d903149ecf84c297a783f37268e2f1a/subzero-core/src/main/java/info/jerrinot/subzero/UserSerializer.java#L33-L33). 
You can either provide your own implementation - this gives you a full control - or you can use convenient builder-like methods:
```java
import static info.jerrinot.subzero.UserSerializer.register;
[...]

public static class MySerializer extends Serializer<MyObject> {

  public MySerializer() {
    super(MyObject.class);
  }

  @Override
  public UserSerializer userSerializers() {
    return register(MyObject.class,   new MyCustomKryoSerializer())
          .register(OtherClass.class, new OtherKryoSerializer());
  }
}
```
I appreciate your feedback on the registration options. 
I'm still not satisfied with the `UserSerializer` interface, but it's getting there.

**Comment by jerrinot** [comment]
@wneild: did you have a chance to look at the prototype?

**Comment by thekalinga** [comment]
@jerrinot 
Why `Serializer<MyObject>` is registering `OtherClass`?

**Comment by jerrinot** [comment]
@wneild: yeah, it shouldn't be in the example. 

The idea is to allow SubZero `Serializer` to be subclassable even for usage as a global serializer - and in this case you might want to register multiple Kryo user Serializers. 

In most cases it shouldn't be needed, just the property file should be enough.

**Comment by jerrinot** [comment]
so the example should look like this:
```java
import static info.jerrinot.subzero.UserSerializerConfig.register;
[...]

public static class MySerializer extends Serializer<MyObject> {

  public MySerializer() {
    super(MyObject.class);
  }

  @Override
  public UserSerializer userSerializers() {
    return register(MyObject.class,   new MyCustomKryoSerializer());
  }
}
```

**Comment by wneild** [comment]
@jerrinot looks good: the properties file is a great fit. My only concern is the design to override the userSerializers method to add custom serialization for a type as the user should be restricted to only being allowed to register a single custom serializer for a type. Unless there is a case you would want to register multiple Kyro serializers for a single type?

I've made some changes based on this feedback here: https://github.com/jerrinot/subzero/pull/7

Let me know what you think but otherwise great work adding this functionality so fast!

**Comment by jerrinot** [comment]
fixed in the current master.
